package com.wx.movie.data.dao.mapper.order;

import com.wx.movie.data.dao.entity.order.MovieDetail;

public interface MovieDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_detail
     *
     * @mbggenerated
     */
    int insert(MovieDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_detail
     *
     * @mbggenerated
     */
    int insertSelective(MovieDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_detail
     *
     * @mbggenerated
     */
    MovieDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MovieDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MovieDetail record);
}