package com.wx.movie.data.dao.mapper.user;

import com.wx.movie.data.dao.entity.user.OpenBaseMovie;

public interface OpenBaseMovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_base_movie
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_base_movie
     *
     * @mbggenerated
     */
    int insert(OpenBaseMovie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_base_movie
     *
     * @mbggenerated
     */
    int insertSelective(OpenBaseMovie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_base_movie
     *
     * @mbggenerated
     */
    OpenBaseMovie selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_base_movie
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OpenBaseMovie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_base_movie
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OpenBaseMovie record);
}