package com.wx.movie.data.dao.mapper.user;

import com.wx.movie.data.dao.entity.user.UserComment;

public interface UserCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbggenerated
     */
    int insert(UserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbggenerated
     */
    int insertSelective(UserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbggenerated
     */
    UserComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserComment record);
}