package com.wx.movie.data.dao.mapper.user;

import com.wx.movie.data.dao.entity.user.UserLike;

public interface UserLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbggenerated
     */
    int insert(UserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbggenerated
     */
    int insertSelective(UserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbggenerated
     */
    UserLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserLike record);
}