package com.wx.movie.data.dao.entity.user;

import java.util.Date;

public class OpenBaseMovie {
    private Integer id;
    private String movieno;
    private String movienamechs;
    private String movienameeng;
    private String movienamepinyin;
    private String movienameinitpinyin;
    private String director;
    private String screenwriter;
    private String starring;
    private String movietype;
    private String contry;
    private Date firstshow;
    private String duration;
    private String moviedetail;
    private String version;
    private String inshortremark;
    private Short islock;
    private String movieurl;
    private Short sourcetype;
    private Short type;
    private Short status;

    private String creatorid;
    private Date createtime;

    private String editerid;

    private Date edittime;

    private String mongocheckcode;

    private String score;
    private Boolean ispast;
 
    public Integer getId() {
      return id;
    }

    public void setId(Integer id) {
      this.id = id;
    }


    public Boolean getIspast() {
      return ispast;
    }

    public void setIspast(Boolean ispast) {
      this.ispast = ispast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.MovieNo
     *
     * @return the value of open_base_movie.MovieNo
     *
     * @mbggenerated
     */
    public String getMovieno() {
        return movieno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.MovieNo
     *
     * @param movieno the value for open_base_movie.MovieNo
     *
     * @mbggenerated
     */
    public void setMovieno(String movieno) {
        this.movieno = movieno == null ? null : movieno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.MovieNameChs
     *
     * @return the value of open_base_movie.MovieNameChs
     *
     * @mbggenerated
     */
    public String getMovienamechs() {
        return movienamechs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.MovieNameChs
     *
     * @param movienamechs the value for open_base_movie.MovieNameChs
     *
     * @mbggenerated
     */
    public void setMovienamechs(String movienamechs) {
        this.movienamechs = movienamechs == null ? null : movienamechs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.MovieNameEng
     *
     * @return the value of open_base_movie.MovieNameEng
     *
     * @mbggenerated
     */
    public String getMovienameeng() {
        return movienameeng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.MovieNameEng
     *
     * @param movienameeng the value for open_base_movie.MovieNameEng
     *
     * @mbggenerated
     */
    public void setMovienameeng(String movienameeng) {
        this.movienameeng = movienameeng == null ? null : movienameeng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.MovieNamePinyin
     *
     * @return the value of open_base_movie.MovieNamePinyin
     *
     * @mbggenerated
     */
    public String getMovienamepinyin() {
        return movienamepinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.MovieNamePinyin
     *
     * @param movienamepinyin the value for open_base_movie.MovieNamePinyin
     *
     * @mbggenerated
     */
    public void setMovienamepinyin(String movienamepinyin) {
        this.movienamepinyin = movienamepinyin == null ? null : movienamepinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.MovieNameInitPinyin
     *
     * @return the value of open_base_movie.MovieNameInitPinyin
     *
     * @mbggenerated
     */
    public String getMovienameinitpinyin() {
        return movienameinitpinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.MovieNameInitPinyin
     *
     * @param movienameinitpinyin the value for open_base_movie.MovieNameInitPinyin
     *
     * @mbggenerated
     */
    public void setMovienameinitpinyin(String movienameinitpinyin) {
        this.movienameinitpinyin = movienameinitpinyin == null ? null : movienameinitpinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.Director
     *
     * @return the value of open_base_movie.Director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.Director
     *
     * @param director the value for open_base_movie.Director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.Screenwriter
     *
     * @return the value of open_base_movie.Screenwriter
     *
     * @mbggenerated
     */
    public String getScreenwriter() {
        return screenwriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.Screenwriter
     *
     * @param screenwriter the value for open_base_movie.Screenwriter
     *
     * @mbggenerated
     */
    public void setScreenwriter(String screenwriter) {
        this.screenwriter = screenwriter == null ? null : screenwriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.Starring
     *
     * @return the value of open_base_movie.Starring
     *
     * @mbggenerated
     */
    public String getStarring() {
        return starring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.Starring
     *
     * @param starring the value for open_base_movie.Starring
     *
     * @mbggenerated
     */
    public void setStarring(String starring) {
        this.starring = starring == null ? null : starring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.MovieType
     *
     * @return the value of open_base_movie.MovieType
     *
     * @mbggenerated
     */
    public String getMovietype() {
        return movietype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.MovieType
     *
     * @param movietype the value for open_base_movie.MovieType
     *
     * @mbggenerated
     */
    public void setMovietype(String movietype) {
        this.movietype = movietype == null ? null : movietype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.Contry
     *
     * @return the value of open_base_movie.Contry
     *
     * @mbggenerated
     */
    public String getContry() {
        return contry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.Contry
     *
     * @param contry the value for open_base_movie.Contry
     *
     * @mbggenerated
     */
    public void setContry(String contry) {
        this.contry = contry == null ? null : contry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.FirstShow
     *
     * @return the value of open_base_movie.FirstShow
     *
     * @mbggenerated
     */
    public Date getFirstshow() {
        return firstshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.FirstShow
     *
     * @param firstshow the value for open_base_movie.FirstShow
     *
     * @mbggenerated
     */
    public void setFirstshow(Date firstshow) {
        this.firstshow = firstshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.Duration
     *
     * @return the value of open_base_movie.Duration
     *
     * @mbggenerated
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.Duration
     *
     * @param duration the value for open_base_movie.Duration
     *
     * @mbggenerated
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.MovieDetail
     *
     * @return the value of open_base_movie.MovieDetail
     *
     * @mbggenerated
     */
    public String getMoviedetail() {
        return moviedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.MovieDetail
     *
     * @param moviedetail the value for open_base_movie.MovieDetail
     *
     * @mbggenerated
     */
    public void setMoviedetail(String moviedetail) {
        this.moviedetail = moviedetail == null ? null : moviedetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.Version
     *
     * @return the value of open_base_movie.Version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.Version
     *
     * @param version the value for open_base_movie.Version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.InShortRemark
     *
     * @return the value of open_base_movie.InShortRemark
     *
     * @mbggenerated
     */
    public String getInshortremark() {
        return inshortremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.InShortRemark
     *
     * @param inshortremark the value for open_base_movie.InShortRemark
     *
     * @mbggenerated
     */
    public void setInshortremark(String inshortremark) {
        this.inshortremark = inshortremark == null ? null : inshortremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.IsLock
     *
     * @return the value of open_base_movie.IsLock
     *
     * @mbggenerated
     */
    public Short getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.IsLock
     *
     * @param islock the value for open_base_movie.IsLock
     *
     * @mbggenerated
     */
    public void setIslock(Short islock) {
        this.islock = islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.MovieUrl
     *
     * @return the value of open_base_movie.MovieUrl
     *
     * @mbggenerated
     */
    public String getMovieurl() {
        return movieurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.MovieUrl
     *
     * @param movieurl the value for open_base_movie.MovieUrl
     *
     * @mbggenerated
     */
    public void setMovieurl(String movieurl) {
        this.movieurl = movieurl == null ? null : movieurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.SourceType
     *
     * @return the value of open_base_movie.SourceType
     *
     * @mbggenerated
     */
    public Short getSourcetype() {
        return sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.SourceType
     *
     * @param sourcetype the value for open_base_movie.SourceType
     *
     * @mbggenerated
     */
    public void setSourcetype(Short sourcetype) {
        this.sourcetype = sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.Type
     *
     * @return the value of open_base_movie.Type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.Type
     *
     * @param type the value for open_base_movie.Type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.Status
     *
     * @return the value of open_base_movie.Status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.Status
     *
     * @param status the value for open_base_movie.Status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.CreatorID
     *
     * @return the value of open_base_movie.CreatorID
     *
     * @mbggenerated
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.CreatorID
     *
     * @param creatorid the value for open_base_movie.CreatorID
     *
     * @mbggenerated
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.CreateTime
     *
     * @return the value of open_base_movie.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.CreateTime
     *
     * @param createtime the value for open_base_movie.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.EditerID
     *
     * @return the value of open_base_movie.EditerID
     *
     * @mbggenerated
     */
    public String getEditerid() {
        return editerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.EditerID
     *
     * @param editerid the value for open_base_movie.EditerID
     *
     * @mbggenerated
     */
    public void setEditerid(String editerid) {
        this.editerid = editerid == null ? null : editerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.EditTime
     *
     * @return the value of open_base_movie.EditTime
     *
     * @mbggenerated
     */
    public Date getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.EditTime
     *
     * @param edittime the value for open_base_movie.EditTime
     *
     * @mbggenerated
     */
    public void setEdittime(Date edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.MongoCheckCode
     *
     * @return the value of open_base_movie.MongoCheckCode
     *
     * @mbggenerated
     */
    public String getMongocheckcode() {
        return mongocheckcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.MongoCheckCode
     *
     * @param mongocheckcode the value for open_base_movie.MongoCheckCode
     *
     * @mbggenerated
     */
    public void setMongocheckcode(String mongocheckcode) {
        this.mongocheckcode = mongocheckcode == null ? null : mongocheckcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_base_movie.Score
     *
     * @return the value of open_base_movie.Score
     *
     * @mbggenerated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_base_movie.Score
     *
     * @param score the value for open_base_movie.Score
     *
     * @mbggenerated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }
}