package com.wx.movie.data.dao.entity.user;


public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.mobileNo
     *
     * @mbggenerated
     */
    private String mobileno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.openId
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.nikeName
     *
     * @mbggenerated
     */
    private String nikename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.photo
     *
     * @mbggenerated
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.unionId
     *
     * @mbggenerated
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.otherId
     *
     * @mbggenerated
     */
    private Integer otherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.platForm
     *
     * @mbggenerated
     */
    private Boolean platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.isDel
     *
     * @mbggenerated
     */
    private Boolean isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.uid
     *
     * @return the value of t_users.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.uid
     *
     * @param uid the value for t_users.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.mobileNo
     *
     * @return the value of t_users.mobileNo
     *
     * @mbggenerated
     */
    public String getMobileno() {
        return mobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.mobileNo
     *
     * @param mobileno the value for t_users.mobileNo
     *
     * @mbggenerated
     */
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno == null ? null : mobileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.password
     *
     * @return the value of t_users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.password
     *
     * @param password the value for t_users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.openId
     *
     * @return the value of t_users.openId
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.openId
     *
     * @param openid the value for t_users.openId
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.nikeName
     *
     * @return the value of t_users.nikeName
     *
     * @mbggenerated
     */
    public String getNikename() {
        return nikename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.nikeName
     *
     * @param nikename the value for t_users.nikeName
     *
     * @mbggenerated
     */
    public void setNikename(String nikename) {
        this.nikename = nikename == null ? null : nikename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.photo
     *
     * @return the value of t_users.photo
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.photo
     *
     * @param photo the value for t_users.photo
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.unionId
     *
     * @return the value of t_users.unionId
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.unionId
     *
     * @param unionid the value for t_users.unionId
     *
     * @mbggenerated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.otherId
     *
     * @return the value of t_users.otherId
     *
     * @mbggenerated
     */
    public Integer getOtherid() {
        return otherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.otherId
     *
     * @param otherid the value for t_users.otherId
     *
     * @mbggenerated
     */
    public void setOtherid(Integer otherid) {
        this.otherid = otherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.platForm
     *
     * @return the value of t_users.platForm
     *
     * @mbggenerated
     */
    public Boolean getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.platForm
     *
     * @param platform the value for t_users.platForm
     *
     * @mbggenerated
     */
    public void setPlatform(Boolean platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.isDel
     *
     * @return the value of t_users.isDel
     *
     * @mbggenerated
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.isDel
     *
     * @param isdel the value for t_users.isDel
     *
     * @mbggenerated
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }
}