package com.wx.movie.data.dao.entity.order;

import java.util.Date;

public class MovieDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.film_no
     *
     * @mbggenerated
     */
    private Integer filmNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.cinema_no
     *
     * @mbggenerated
     */
    private Integer cinemaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.cinema_name
     *
     * @mbggenerated
     */
    private String cinemaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.film_name
     *
     * @mbggenerated
     */
    private String filmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.hall_no
     *
     * @mbggenerated
     */
    private String hallNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.hall_name
     *
     * @mbggenerated
     */
    private String hallName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.base_schedule_id
     *
     * @mbggenerated
     */
    private Integer baseScheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.schedule_record_id
     *
     * @mbggenerated
     */
    private Integer scheduleRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.show_type
     *
     * @mbggenerated
     */
    private String showType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.language
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.center_order_id
     *
     * @mbggenerated
     */
    private Integer centerOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.tp_order_id
     *
     * @mbggenerated
     */
    private String tpOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.first_code
     *
     * @mbggenerated
     */
    private String firstCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.second_code
     *
     * @mbggenerated
     */
    private String secondCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.code_type
     *
     * @mbggenerated
     */
    private Integer codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.bis_id
     *
     * @mbggenerated
     */
    private String bisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.bis_server_id
     *
     * @mbggenerated
     */
    private String bisServerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.show_time
     *
     * @mbggenerated
     */
    private Date showTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.cost_price
     *
     * @mbggenerated
     */
    private Integer costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.sale_price
     *
     * @mbggenerated
     */
    private Integer salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.seat_info
     *
     * @mbggenerated
     */
    private String seatInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.pay_status
     *
     * @mbggenerated
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.refund_type
     *
     * @mbggenerated
     */
    private Integer refundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.lock_time
     *
     * @mbggenerated
     */
    private Date lockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.unlock_time
     *
     * @mbggenerated
     */
    private Date unlockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.sell_ticket_time
     *
     * @mbggenerated
     */
    private Date sellTicketTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.print_ticket_time
     *
     * @mbggenerated
     */
    private Date printTicketTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.refund_ticket_time
     *
     * @mbggenerated
     */
    private Date refundTicketTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_detail.qrcode
     *
     * @mbggenerated
     */
    private String qrcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.id
     *
     * @return the value of movie_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.id
     *
     * @param id the value for movie_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.film_no
     *
     * @return the value of movie_detail.film_no
     *
     * @mbggenerated
     */
    public Integer getFilmNo() {
        return filmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.film_no
     *
     * @param filmNo the value for movie_detail.film_no
     *
     * @mbggenerated
     */
    public void setFilmNo(Integer filmNo) {
        this.filmNo = filmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.cinema_no
     *
     * @return the value of movie_detail.cinema_no
     *
     * @mbggenerated
     */
    public Integer getCinemaNo() {
        return cinemaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.cinema_no
     *
     * @param cinemaNo the value for movie_detail.cinema_no
     *
     * @mbggenerated
     */
    public void setCinemaNo(Integer cinemaNo) {
        this.cinemaNo = cinemaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.cinema_name
     *
     * @return the value of movie_detail.cinema_name
     *
     * @mbggenerated
     */
    public String getCinemaName() {
        return cinemaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.cinema_name
     *
     * @param cinemaName the value for movie_detail.cinema_name
     *
     * @mbggenerated
     */
    public void setCinemaName(String cinemaName) {
        this.cinemaName = cinemaName == null ? null : cinemaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.film_name
     *
     * @return the value of movie_detail.film_name
     *
     * @mbggenerated
     */
    public String getFilmName() {
        return filmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.film_name
     *
     * @param filmName the value for movie_detail.film_name
     *
     * @mbggenerated
     */
    public void setFilmName(String filmName) {
        this.filmName = filmName == null ? null : filmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.hall_no
     *
     * @return the value of movie_detail.hall_no
     *
     * @mbggenerated
     */
    public String getHallNo() {
        return hallNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.hall_no
     *
     * @param hallNo the value for movie_detail.hall_no
     *
     * @mbggenerated
     */
    public void setHallNo(String hallNo) {
        this.hallNo = hallNo == null ? null : hallNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.hall_name
     *
     * @return the value of movie_detail.hall_name
     *
     * @mbggenerated
     */
    public String getHallName() {
        return hallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.hall_name
     *
     * @param hallName the value for movie_detail.hall_name
     *
     * @mbggenerated
     */
    public void setHallName(String hallName) {
        this.hallName = hallName == null ? null : hallName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.base_schedule_id
     *
     * @return the value of movie_detail.base_schedule_id
     *
     * @mbggenerated
     */
    public Integer getBaseScheduleId() {
        return baseScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.base_schedule_id
     *
     * @param baseScheduleId the value for movie_detail.base_schedule_id
     *
     * @mbggenerated
     */
    public void setBaseScheduleId(Integer baseScheduleId) {
        this.baseScheduleId = baseScheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.schedule_record_id
     *
     * @return the value of movie_detail.schedule_record_id
     *
     * @mbggenerated
     */
    public Integer getScheduleRecordId() {
        return scheduleRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.schedule_record_id
     *
     * @param scheduleRecordId the value for movie_detail.schedule_record_id
     *
     * @mbggenerated
     */
    public void setScheduleRecordId(Integer scheduleRecordId) {
        this.scheduleRecordId = scheduleRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.show_type
     *
     * @return the value of movie_detail.show_type
     *
     * @mbggenerated
     */
    public String getShowType() {
        return showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.show_type
     *
     * @param showType the value for movie_detail.show_type
     *
     * @mbggenerated
     */
    public void setShowType(String showType) {
        this.showType = showType == null ? null : showType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.language
     *
     * @return the value of movie_detail.language
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.language
     *
     * @param language the value for movie_detail.language
     *
     * @mbggenerated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.center_order_id
     *
     * @return the value of movie_detail.center_order_id
     *
     * @mbggenerated
     */
    public Integer getCenterOrderId() {
        return centerOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.center_order_id
     *
     * @param centerOrderId the value for movie_detail.center_order_id
     *
     * @mbggenerated
     */
    public void setCenterOrderId(Integer centerOrderId) {
        this.centerOrderId = centerOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.tp_order_id
     *
     * @return the value of movie_detail.tp_order_id
     *
     * @mbggenerated
     */
    public String getTpOrderId() {
        return tpOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.tp_order_id
     *
     * @param tpOrderId the value for movie_detail.tp_order_id
     *
     * @mbggenerated
     */
    public void setTpOrderId(String tpOrderId) {
        this.tpOrderId = tpOrderId == null ? null : tpOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.first_code
     *
     * @return the value of movie_detail.first_code
     *
     * @mbggenerated
     */
    public String getFirstCode() {
        return firstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.first_code
     *
     * @param firstCode the value for movie_detail.first_code
     *
     * @mbggenerated
     */
    public void setFirstCode(String firstCode) {
        this.firstCode = firstCode == null ? null : firstCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.second_code
     *
     * @return the value of movie_detail.second_code
     *
     * @mbggenerated
     */
    public String getSecondCode() {
        return secondCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.second_code
     *
     * @param secondCode the value for movie_detail.second_code
     *
     * @mbggenerated
     */
    public void setSecondCode(String secondCode) {
        this.secondCode = secondCode == null ? null : secondCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.code_type
     *
     * @return the value of movie_detail.code_type
     *
     * @mbggenerated
     */
    public Integer getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.code_type
     *
     * @param codeType the value for movie_detail.code_type
     *
     * @mbggenerated
     */
    public void setCodeType(Integer codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.bis_id
     *
     * @return the value of movie_detail.bis_id
     *
     * @mbggenerated
     */
    public String getBisId() {
        return bisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.bis_id
     *
     * @param bisId the value for movie_detail.bis_id
     *
     * @mbggenerated
     */
    public void setBisId(String bisId) {
        this.bisId = bisId == null ? null : bisId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.bis_server_id
     *
     * @return the value of movie_detail.bis_server_id
     *
     * @mbggenerated
     */
    public String getBisServerId() {
        return bisServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.bis_server_id
     *
     * @param bisServerId the value for movie_detail.bis_server_id
     *
     * @mbggenerated
     */
    public void setBisServerId(String bisServerId) {
        this.bisServerId = bisServerId == null ? null : bisServerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.show_time
     *
     * @return the value of movie_detail.show_time
     *
     * @mbggenerated
     */
    public Date getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.show_time
     *
     * @param showTime the value for movie_detail.show_time
     *
     * @mbggenerated
     */
    public void setShowTime(Date showTime) {
        this.showTime = showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.cost_price
     *
     * @return the value of movie_detail.cost_price
     *
     * @mbggenerated
     */
    public Integer getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.cost_price
     *
     * @param costPrice the value for movie_detail.cost_price
     *
     * @mbggenerated
     */
    public void setCostPrice(Integer costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.sale_price
     *
     * @return the value of movie_detail.sale_price
     *
     * @mbggenerated
     */
    public Integer getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.sale_price
     *
     * @param salePrice the value for movie_detail.sale_price
     *
     * @mbggenerated
     */
    public void setSalePrice(Integer salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.num
     *
     * @return the value of movie_detail.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.num
     *
     * @param num the value for movie_detail.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.seat_info
     *
     * @return the value of movie_detail.seat_info
     *
     * @mbggenerated
     */
    public String getSeatInfo() {
        return seatInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.seat_info
     *
     * @param seatInfo the value for movie_detail.seat_info
     *
     * @mbggenerated
     */
    public void setSeatInfo(String seatInfo) {
        this.seatInfo = seatInfo == null ? null : seatInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.status
     *
     * @return the value of movie_detail.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.status
     *
     * @param status the value for movie_detail.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.pay_status
     *
     * @return the value of movie_detail.pay_status
     *
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.pay_status
     *
     * @param payStatus the value for movie_detail.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.refund_type
     *
     * @return the value of movie_detail.refund_type
     *
     * @mbggenerated
     */
    public Integer getRefundType() {
        return refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.refund_type
     *
     * @param refundType the value for movie_detail.refund_type
     *
     * @mbggenerated
     */
    public void setRefundType(Integer refundType) {
        this.refundType = refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.lock_time
     *
     * @return the value of movie_detail.lock_time
     *
     * @mbggenerated
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.lock_time
     *
     * @param lockTime the value for movie_detail.lock_time
     *
     * @mbggenerated
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.unlock_time
     *
     * @return the value of movie_detail.unlock_time
     *
     * @mbggenerated
     */
    public Date getUnlockTime() {
        return unlockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.unlock_time
     *
     * @param unlockTime the value for movie_detail.unlock_time
     *
     * @mbggenerated
     */
    public void setUnlockTime(Date unlockTime) {
        this.unlockTime = unlockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.sell_ticket_time
     *
     * @return the value of movie_detail.sell_ticket_time
     *
     * @mbggenerated
     */
    public Date getSellTicketTime() {
        return sellTicketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.sell_ticket_time
     *
     * @param sellTicketTime the value for movie_detail.sell_ticket_time
     *
     * @mbggenerated
     */
    public void setSellTicketTime(Date sellTicketTime) {
        this.sellTicketTime = sellTicketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.print_ticket_time
     *
     * @return the value of movie_detail.print_ticket_time
     *
     * @mbggenerated
     */
    public Date getPrintTicketTime() {
        return printTicketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.print_ticket_time
     *
     * @param printTicketTime the value for movie_detail.print_ticket_time
     *
     * @mbggenerated
     */
    public void setPrintTicketTime(Date printTicketTime) {
        this.printTicketTime = printTicketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.refund_ticket_time
     *
     * @return the value of movie_detail.refund_ticket_time
     *
     * @mbggenerated
     */
    public Date getRefundTicketTime() {
        return refundTicketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.refund_ticket_time
     *
     * @param refundTicketTime the value for movie_detail.refund_ticket_time
     *
     * @mbggenerated
     */
    public void setRefundTicketTime(Date refundTicketTime) {
        this.refundTicketTime = refundTicketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.order_id
     *
     * @return the value of movie_detail.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.order_id
     *
     * @param orderId the value for movie_detail.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.open_id
     *
     * @return the value of movie_detail.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.open_id
     *
     * @param openId the value for movie_detail.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_detail.qrcode
     *
     * @return the value of movie_detail.qrcode
     *
     * @mbggenerated
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_detail.qrcode
     *
     * @param qrcode the value for movie_detail.qrcode
     *
     * @mbggenerated
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode == null ? null : qrcode.trim();
    }
}